remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: AI Town: A Virtual Environment for Interaction Between Generative Agents
author: Siyu Chen, Yexiaolu He, Jinxin Xiao, Celine Zhao 
